config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get 'sessions/destroy'
  resources :users
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  def index
    @movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def new
    @movie = Movie.new
  end


  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    @movie.save(validate: false)
    redirect_to root_url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:user_id, :title, :description, :url, :likes, :dislikes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :search_user, only: [:create]

  def create
    if not @user.nil? 
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
      end
    else
      @user = User.new(user_params)
      @user.save
      session[:user_id] = @user.id
    end
    redirect_to root_path
  end

  private

    def search_user
      @user = User.find_by_email(params[:user][:email])
    end
        
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
   User.find_by_id session[:user_id]
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="row">
  <div class="col">
      <br><br>
      <% @movies.each do |movie| %>
        <div class="row mb-3">
          <div class="col">
            <%= YouTubeRails.youtube_embed_url(movie.url, 420, 315, ssl: true).html_safe  %>
          </div>
          <div class="col">
            <% 
              video = Yt::Video.new id: YouTubeRails.extract_video_id(movie.url)  
            %>
            <h5 class="text-danger"><%= video.title %></h5>
            <p class="m-0">
              Shared by: <strong><%= movie.user.email %></strong>
            </p>
            <p class="m-0">
              <span class="mr-2"><%= video.like_count %>   <%= fa_icon "thumbs-o-up" %></span>
              <span><%= video.dislike_count %>   <%= fa_icon "thumbs-o-down" %></span>
            </p>
            <p>
              <label for="description">Description:</label> <br>
              <%= truncate(video.description, length: 50, omission: '... (continued)')  %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtubeshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="container">
          <%= render partial: 'partials/header' %>
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col">
    <div class="card mt-5">
        <div class="card-body">
            <%= form_with(model: movie, local: true) do |form| %>
            <fieldset>
              <legend>Share a Youtube movie</legend>
              <%= form.label :url, 'Youtube URL:' %>
              <%= form.text_field :url, class: 'form-control' %>
              <button class="btn btn-outline-success btn-block mt-2" type="submit">Share</button>
            </fieldset>
          <% end %>
        </div>
      </div>
  </div>
  <div class="col"></div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Url</th>
      <th>Likes</th>
      <th>Dislikes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.user %></td>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.url %></td>
        <td><%= movie.likes %></td>
        <td><%= movie.dislikes %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @movie.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @movie.url %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @movie.likes %>
</p>

<p>
  <strong>Dislikes:</strong>
  <%= @movie.dislikes %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/partials/_form.html.erb
<%= form_with(model: User.new, local: true, class: 'form-inline my-2 my-lg-0') do |form| %>
  <%= form.text_field :email, class: 'form-control mr-sm-2', placeholder: 'Email'  %>
  <%= form.password_field :password,  class: 'form-control mr-sm-2', placeholder: 'Password' %>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login/Register</button>
<% end %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
       <%= fa_icon "home", text: 'Funny Movies' %>
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <% if current_user.nil? %>
        <%= render partial: 'partials/form' %>
      <% else %>
        <%= render partial: 'partials/logged_in' %>
      <% end %>
     
    </div>
  </nav>

app/views/partials/_logged_in.html.erb
<span class="mr-3">Welcome <%= current_user.email %>  </span>
<%= link_to 'Share a movie', new_movie_url, class: 'btn btn-outline-success my-2 my-sm-0 mr-2' %>
<%= link_to 'Logout', sessions_destroy_url , class: 'btn btn-outline-primary my-2 my-sm-0' %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>